
#  =/h2-console
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    console.enabled: true
    console.path: /console

logging:
  level:
    jdbc:
      sqlonly: OFF
      sqltiming: DEBUG
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG
      connection: OFF
    com.tjlee: DEBUG
    org.hibernate.SQL: WARN